// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuFyXmMu-Q_YJnZMqMSRdNTeiInqMWKzw',
    appId: '1:637337114062:web:a83ff890dafd560b34879f',
    messagingSenderId: '637337114062',
    projectId: 'tradingalerts-3e0d7',
    authDomain: 'tradingalerts-3e0d7.firebaseapp.com',
    storageBucket: 'tradingalerts-3e0d7.firebasestorage.app',
    measurementId: 'G-3VTH0PP87L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_hWIPT8DRc-Il21w8F7hk5xoB2ir3EF8',
    appId: '1:637337114062:android:6f4318ed8be102ad34879f',
    messagingSenderId: '637337114062',
    projectId: 'tradingalerts-3e0d7',
    storageBucket: 'tradingalerts-3e0d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-gUakHAqCeRpB9h8Vhd7Q0kSzsLFBAn8',
    appId: '1:637337114062:ios:c24011e4e2b171ef34879f',
    messagingSenderId: '637337114062',
    projectId: 'tradingalerts-3e0d7',
    storageBucket: 'tradingalerts-3e0d7.firebasestorage.app',
    iosBundleId: 'com.example.stocksalertapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-gUakHAqCeRpB9h8Vhd7Q0kSzsLFBAn8',
    appId: '1:637337114062:ios:c24011e4e2b171ef34879f',
    messagingSenderId: '637337114062',
    projectId: 'tradingalerts-3e0d7',
    storageBucket: 'tradingalerts-3e0d7.firebasestorage.app',
    iosBundleId: 'com.example.stocksalertapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuFyXmMu-Q_YJnZMqMSRdNTeiInqMWKzw',
    appId: '1:637337114062:web:66397581eca11b0134879f',
    messagingSenderId: '637337114062',
    projectId: 'tradingalerts-3e0d7',
    authDomain: 'tradingalerts-3e0d7.firebaseapp.com',
    storageBucket: 'tradingalerts-3e0d7.firebasestorage.app',
    measurementId: 'G-DCMW60M1WG',
  );
}